### ISSUE TITLE
Prevent scrolling on mobile

### ISSUE THREAD

**Issue by gushecht** [thorgate/tg-modal#21] opened 2016-11-23 16:52 UTC
I have been searching for a modal that prevents scrolling on the underlying body when the modal is displayed.  Looks like this library does that on desktop, but on mobile browsers (I've tried Safari and Chrome on iOS) the body scrolls.  This is particularly problematic because the URL bar and/or bottom toolbar (depending on the browser) shrink when scrolling down.  When that happens, we see  underneath the modal, since the size of the modal was set when the URL bar and toolbar are displayed.

Thoughts on a resolution?

**Comment by Jyrno42** [comment] 2016-12-07 11:20
I will be looking into this in the following weeks.

**Comment by amPerl** [comment] 2016-12-13 12:57
It seems that this issue isn't avoidable without horrible hacks (if even then). I had a look at some of the top modal libraries for React and none of them seem to solve this problem either. The best I can do is extend the backdrop to cover the part that is revealed on navbar-scroll, but it doesn't stop the modal contents from jumping once the resize ends.

What do you think should be the expected behaviour in this case? Do you have any suggestions or know of a library that seems to have fixed this problem?

**Comment by schryer** [comment] 2016-12-14 06:00
Perhaps we can resize the backdrop after the end resize event (or after any
change in the view size).

**Comment by gushecht** [comment] 2016-12-16 00:26
I ended up using stopPropagation and preventDefault when the modal was open. Perhaps that can work?

**Comment by amPerl** [comment] 2016-12-16 09:41
Could you show an example of your solution? (codepen or similar)

Also relevant:

Looks like this navbar issue is being dealt with in Chrome: https://bugs.chromium.org/p/chromium/issues/detail?id=428132

There's also HTML `dialog` elements to look forward to. They only seem to be implemented on Chromium-based browsers and Opera right now though. http://caniuse.com/#feat=dialog

**Comment by gushecht** [comment] 2017-01-19 16:51
Apologies for the major delay!

Can't take the time for Codepen right now, but hopefully the explanation below is sufficient:

Within my component, I use three lifecycle methods:

**Comment by pahomov** [comment] 2018-05-10 15:16
https://github.com/pradel/react-responsive-modal
https://github.com/davidtheclark/react-aria-modal
these two dealt with scroll prevention pretty well via `document.querySelector('html').style.position = 'fixed';`

**Comment by Jyrno42** [comment] 2019-06-13 13:31
#54 adds `position: fixed` to `body.tg-modal-open` in default styles. Please note that one might also need to add `min-width: 100vw;` to avoid style issues with body while modals are open. 

It will be released soon as `0.9.0-beta.0`

**Closed by Jyrno42** 2019-06-13 13:31 UTC

**Comment by Jyrno42** [comment] 2019-06-25 13:18
0.9.0 which contains fix for this issue has been released
